### PR TITLE
Updated avrdude, avrdude.conf and avr-size

### PR DESCRIPTION
**Pull request by LumitoLuma**
Now uses Arduino's latest release of AVRDUDE (6.3-20210108). This includes support for newer boards (i.e. ATmega4809) and programmers (i.e. Atmel AVR Xplained Mini in UPDI mode).

Also I've made a translation for the program (Spanish), but some words doesn't show well in the final program. I leave here the translation if you want it:

[spanish.xml.txt](https://github.com/zkemble/AVRDUDESS/files/6213058/spanish.xml.txt) (Rename to spanish.xml)

Also, I've updated the avrdude.conf file (to support newer boards) and avr-size, since it was pretty old.

### CODE REVIEW

**Comment by zkemble** [comment]
Heya, where are these files from? They seem to be different than the ones from the latest Arduino 1.8.13 and nightly releases.

**Comment by LumitoLuma** [comment]
You are right. I found this URL: https://downloads.arduino.cc/tools/avrdude-6.3.0-arduino17-i686-w64-mingw32.zip and I changed arduino17 with arduino18 and worked. AVRDUDE binary is from this package: https://downloads.arduino.cc/tools/avrdude-6.3.0-arduino18-i686-w64-mingw32.zip. Tested with various Arduino boards without problems. Avr-size is from your latest avr-gcc build.

**Comment by zkemble** [comment]
Ah ok, though the Arduino avrdude.conf doesn't have support for the ATmega16U4 (https://github.com/zkemble/AVRDUDESS/commit/6de62daaaf917ca5d3cafd1bab2b72c200aa4329) and doesn't have the missing efuse bit fix for the ATmega328PB (https://github.com/zkemble/AVRDUDESS/commit/b9fa7e2a4fa720ba92006bace6aee7fb1678e3eb https://github.com/zkemble/AVRDUDESS/commit/78ee1c4287ff74e3f7fb2afb8841186782b3cf64). I'll merge your stuff when I have time to re-add those things, otherwise I'll probably forget.

Spanish translations look good, could you open a separate pull request for that?

**Comment by LumitoLuma** [comment]
The problem with Spanish translations is that they look weird in the final interface. However, I'll open a new PR if you want it.

**Comment by zkemble** [comment]
Do you mean that some of the words are cut off and overlapping? That's something that I will be working on, a few other translations also have the same problem.

**Comment by LumitoLuma** [comment]
Ok, then I'll open a new PR soon

**Comment by ZakKemble** [comment]
Closing since v7.0 is a thing now which seems to include all of these new parts and programmers, see #60

**Pull request closed without merging**
