### PR TITLE
A lot of minor improvements

### PR DESCRIPTION
**Pull request by LumitoLuma**
I've improved/fixed/added the following things:

- Added 'Default (375 KHz)' option for USBasp
- Fixed a debugging warning
- Re-added the fuse calculator link, since https://www.engbedded.com/fusecalc/ is back online
- Updated &copy; years
- Added build date in about tab
- Other very minor changes

### CODE REVIEW

**Comment by zkemble** [comment]
>     * Added 'auto' option for USBasp

I'm not sure if calling it "Auto" is a good idea, the USBasp firmware just sets it to 375KHz. People will think that it automatically selects the best bit clock. Maybe call it "Default (375KHz)".

>     * Allowed some special characters like `"` and `'` in the AVRDUDE and AVRDUDE.conf location paths

Is this an issue when running AVRDUDESS on Linux? I don't have any problems with ' on Windows and it doesn't let you use " in folder and file names.

>     * Re-added the fuse calculator link, since https://www.engbedded.com/fusecalc/ is back online

\o.o/

>     * Added 'custom programmer option' in Programmers list (translations need to be updated)

What would the use case of this be? If a programmer is not already listed in the drop down then it's not supported by AVRDUDE.

**Comment by LumitoLuma** [comment]
> ```
> * Added 'custom programmer option' in Programmers list (translations need to be updated)
> ```

Totally true. I did that change because I didn't find some programmers, but I wasn't searching in the correct place. I will revert it soon.

> ```
> * Allowed some special characters like `"` and `'` in the AVRDUDE and AVRDUDE.conf location paths
> ```

Yeah, idk why I did that change.

> ```
> * Added 'auto' option for USBasp
> ```

I'm not so sure to change it to "Default (375KHz)". Tried with my usbasp to my Arduino UNO and when selecting 'Auto' it uploads faster than selecting the 375 KHz option (I think it uploads at 1.5 MHz). However, I use a custom firmware for my usbasp. I'll try it with the default one and if it uploads at 375 KHz by default, then I'll change it.

**Comment by LumitoLuma** [comment]
You are right with the USBasp default mode. I'll change the name soon.

**Comment by LumitoLuma** [comment]
Everything should be right now.

**Comment by ZakKemble** [comment]
Chery picked commits (7e043f433e1a57fad7c126bee449196cbe416c93 aa976d61f8e29e6ab477606eb09e60191795c08b dcdcd755b4f426de5ab13ac973ebafd019b2bb5e) to minimize clutter, closing PR.

**Pull request closed without merging**
