### PR TITLE
Optimize MCU detection & Add update control option

### PR DESCRIPTION
**Pull request by RedSnake64**

### CODE REVIEW

**Comment by zkemble** [comment]
Hey Red, looks good, however could you revert the detect MCU change? See #26 Basically with your change, if you're using an USBasp with ATtiny10 selected and then you try to detect an ATmega328, it won't work because it will try to use the TPI protocol. It should be kept as "m8" for now to keep things a bit more consistent. Actually, I think you might have got confused with its purpose, it's supposed to figure out and select the correct MCU for you, not check to see if the programmer can communicate with the selected MCU.

Can you also change _UPDATE translation key to _CHECKFORUPDATES.

Thanks

**Comment by RedSnake64** [comment]
Hi Zak, i'm currently testing the new Attiny series (with UPDI functionality) and had problems with the detection. I'm getting "part ATmega8 has no PDI interface" because the request is done with 'm8'. Now i know the reason. Perhaps i find a way to make both compatible.

> Can you also change _UPDATE translation key to _CHECKFORUPDATES.
yes i will change it

**Comment by RedSnake64** [comment]
Hi Zak, I've added a Auto-Detect option. Perhaps this could be a compromise.

**Comment by zkemble** [comment]
I don't like the new "Auto" check box, it’s very confusing as to what it does. To me it implies that it will automatically choose the MCU for you when you click "Program!" since it blanks out the MCU selection box, but actually it changes the behaviour of the "Detect" button.

**Comment by ZakKemble** [comment]
Cherry picked the update check option in 01c6033440ebac344b383c4ce776cff37634b470

**Comment by vk7kwb** [comment]
Missing program for up loading hex file ,older version worked ok  CanI upload older version to get the older fisk  promrammer

**Pull request closed without merging**
